# Generated by Django 5.2.1 on 2025-06-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
